### ISSUE TITLE
Reset end should be defined synchronously

### ISSUE THREAD

**Issue by tudortimi** [amiq-consulting/amiq_apb#4]
The code for `wait_reset_end` in the config class should be changed to:

virtual task wait_reset_end();
  if(reset_active_level == 0) begin
    @(posedge dut_vif.clk iff dut_vif.reset_n != reset_active_level);
  end
endtask

This is because the protocol specifies behavior in terms of the first clock cycle after reset. This is also when a master should start driving its items, not immediately as the reset is de-asserted.

**Comment by amiq-consulting** [comment]
Or the user can choose to wait (by @ or wait) a clock cycle after the wait_reset_end() call.
