### ISSUE TITLE
Delay in master item

### ISSUE THREAD

**Issue by tudortimi** [amiq-consulting/amiq_apb#5]
It makes more sense to drive any delay cycles for an item **before** actually driving that item and not afterwards.

Reasons:
1. Random delays after reset are possible out of the box, otherwise users have to insert delays themselves
2. The item is marked as finished by finish_item() when it is done

**Comment by amiq-consulting** [comment]
This is a matter of taste. As long as it is consistent through out the VIP/Environment.
